export const LANGUAGES=[
  {code:"vi",label:"Tiếng Việt"},{code:"en",label:"English"},{code:"ko",label:"한국어"},
  {code:"ja",label:"日本語"},{code:"zh",label:"中文"},{code:"th",label:"ภาษาไทย"},
];

const en=["Log in","Register","Create account","Back to login","Full name","Username","Email","Password","Home","Profile","Friends","Messages","Settings","Notifications","Search SocialN...","Create post","What's on your mind?","Write a comment...","Public","Friends","Only me","Privacy","Save","Save changes","Cancel","Delete","Confirm","Edit profile","Albums","Create album","Album name","Description / notes","Write something about this album...","Add photos/videos","Edit album","Delete album","Select media","No photos or videos yet.","Profile pictures, cover photos and timeline media","Friend requests","Your friends","People you may know","Add friend","Message","Personal storage","Start a conversation","Choose someone to message.","Mark all read","Appearance","Choose how SocialN looks on this browser.","Light","Dark","Bright background","Easy on the eyes","Language","Choose the language used across SocialN.","Change username","Change password","Current password","New password","Confirm new password","Bio","Date of birth","Hometown","Gender","Relationship status","Male","Female","Other","Not specified","Prefer not to say","Single","In a relationship","Engaged","Married","It's complicated","No pending requests.","No visible posts.","No posts yet. Create the first post.","Page not found","Go home","Download","React","Send file","Send image or video","Close preview","Conversation actions","Color theme","View full photo","Zoom","Reload SocialN","SocialN encountered a UI error","Unfriend","Archive","Pin","Delete chat"];

const rows={
vi:["Đăng nhập","Đăng ký","Tạo tài khoản","Quay lại đăng nhập","Họ và tên","Tên người dùng","Email","Mật khẩu","Trang chủ","Trang cá nhân","Bạn bè","Tin nhắn","Cài đặt","Thông báo","Tìm kiếm trên SocialN...","Tạo bài viết","Bạn đang nghĩ gì?","Viết bình luận...","Công khai","Bạn bè","Chỉ mình tôi","Quyền riêng tư","Lưu","Lưu thay đổi","Hủy","Xóa","Xác nhận","Chỉnh sửa trang cá nhân","Album","Tạo album","Tên album","Mô tả / ghi chú","Viết điều gì đó về album này...","Thêm ảnh/video","Sửa album","Xóa album","Chọn media","Chưa có ảnh hoặc video.","Ảnh đại diện, ảnh bìa và media dòng thời gian","Lời mời kết bạn","Bạn bè của bạn","Những người bạn có thể biết","Thêm bạn bè","Nhắn tin","Kho cá nhân","Bắt đầu trò chuyện","Chọn một người để nhắn tin.","Đánh dấu tất cả đã đọc","Giao diện","Chọn giao diện hiển thị của SocialN trên trình duyệt này.","Sáng","Tối","Nền sáng","Dịu mắt","Ngôn ngữ","Chọn ngôn ngữ sử dụng trên toàn bộ SocialN.","Đổi tên người dùng","Đổi mật khẩu","Mật khẩu hiện tại","Mật khẩu mới","Xác nhận mật khẩu mới","Tiểu sử","Ngày sinh","Quê quán","Giới tính","Tình trạng quan hệ","Nam","Nữ","Khác","Chưa xác định","Không muốn tiết lộ","Độc thân","Đang hẹn hò","Đã đính hôn","Đã kết hôn","Phức tạp","Không có lời mời đang chờ.","Không có bài viết hiển thị.","Chưa có bài viết. Hãy tạo bài viết đầu tiên.","Không tìm thấy trang","Về trang chủ","Tải xuống","Bày tỏ cảm xúc","Gửi file","Gửi ảnh hoặc video","Đóng xem trước","Tùy chọn cuộc trò chuyện","Chủ đề màu","Xem ảnh đầy đủ","Thu phóng","Tải lại SocialN","SocialN gặp lỗi giao diện","Hủy kết bạn","Lưu trữ","Ghim","Xóa đoạn chat"],
ko:["로그인","가입","계정 만들기","로그인으로 돌아가기","이름","사용자 이름","이메일","비밀번호","홈","프로필","친구","메시지","설정","알림","SocialN 검색...","게시물 만들기","무슨 생각을 하고 계신가요?","댓글 쓰기...","전체 공개","친구","나만 보기","공개 범위","저장","변경 사항 저장","취소","삭제","확인","프로필 수정","앨범","앨범 만들기","앨범 이름","설명 / 메모","앨범에 대해 작성하세요...","사진/동영상 추가","앨범 수정","앨범 삭제","미디어 선택","사진이나 동영상이 없습니다.","프로필 사진, 커버 사진 및 타임라인 미디어","친구 요청","내 친구","알 수도 있는 사람","친구 추가","메시지","개인 저장소","대화 시작","메시지를 보낼 사람을 선택하세요.","모두 읽음","화면 설정","이 브라우저에서 SocialN의 모습을 선택하세요.","라이트","다크","밝은 배경","눈이 편안한 화면","언어","SocialN 전체에서 사용할 언어를 선택하세요.","사용자 이름 변경","비밀번호 변경","현재 비밀번호","새 비밀번호","새 비밀번호 확인","소개","생년월일","고향","성별","관계 상태","남성","여성","기타","지정 안 함","밝히고 싶지 않음","싱글","연애 중","약혼","기혼","복잡함","대기 중인 요청이 없습니다.","표시할 게시물이 없습니다.","게시물이 없습니다. 첫 게시물을 작성하세요.","페이지를 찾을 수 없음","홈으로","다운로드","반응","파일 보내기","사진 또는 동영상 보내기","미리보기 닫기","대화 옵션","색상 테마","전체 사진 보기","확대/축소","SocialN 새로고침","SocialN UI 오류","친구 삭제","보관","고정","채팅 삭제"],
ja:["ログイン","登録","アカウントを作成","ログインに戻る","氏名","ユーザー名","メール","パスワード","ホーム","プロフィール","友達","メッセージ","設定","通知","SocialNを検索...","投稿を作成","今どうしてる？","コメントを書く...","公開","友達","自分のみ","プライバシー","保存","変更を保存","キャンセル","削除","確認","プロフィールを編集","アルバム","アルバムを作成","アルバム名","説明 / メモ","アルバムについて入力...","写真/動画を追加","アルバムを編集","アルバムを削除","メディアを選択","写真や動画はまだありません。","プロフィール写真、カバー写真、タイムラインメディア","友達リクエスト","友達","知り合いかも","友達を追加","メッセージ","個人ストレージ","会話を開始","メッセージ相手を選択してください。","すべて既読にする","外観","このブラウザでのSocialNの表示を選択します。","ライト","ダーク","明るい背景","目に優しい表示","言語","SocialN全体で使用する言語を選択します。","ユーザー名を変更","パスワードを変更","現在のパスワード","新しいパスワード","新しいパスワードを確認","自己紹介","生年月日","出身地","性別","交際ステータス","男性","女性","その他","未指定","回答しない","独身","交際中","婚約中","既婚","複雑な関係","保留中のリクエストはありません。","表示できる投稿はありません。","投稿はまだありません。最初の投稿を作成しましょう。","ページが見つかりません","ホームへ","ダウンロード","リアクション","ファイルを送信","写真または動画を送信","プレビューを閉じる","会話の操作","カラーテーマ","写真を全表示","ズーム","SocialNを再読み込み","SocialN UIエラー","友達を解除","アーカイブ","固定","チャットを削除"],
zh:["登录","注册","创建账户","返回登录","姓名","用户名","邮箱","密码","首页","个人主页","好友","消息","设置","通知","搜索 SocialN...","创建帖子","你在想什么？","写评论...","公开","好友","仅自己","隐私","保存","保存更改","取消","删除","确认","编辑个人资料","相册","创建相册","相册名称","描述 / 备注","写点关于此相册的内容...","添加照片/视频","编辑相册","删除相册","选择媒体","暂无照片或视频。","头像、封面照片和时间线媒体","好友请求","你的好友","你可能认识的人","添加好友","发消息","个人存储","开始聊天","选择聊天对象。","全部标为已读","外观","选择此浏览器中 SocialN 的外观。","浅色","深色","明亮背景","护眼显示","语言","选择整个 SocialN 使用的语言。","更改用户名","更改密码","当前密码","新密码","确认新密码","简介","出生日期","家乡","性别","感情状态","男性","女性","其他","未指定","不愿透露","单身","恋爱中","已订婚","已婚","关系复杂","没有待处理请求。","没有可见帖子。","暂无帖子。创建第一篇帖子吧。","找不到页面","返回首页","下载","回应","发送文件","发送图片或视频","关闭预览","会话操作","颜色主题","查看完整照片","缩放","重新加载 SocialN","SocialN 界面出错","解除好友","归档","置顶","删除聊天"],
th:["เข้าสู่ระบบ","สมัครสมาชิก","สร้างบัญชี","กลับไปเข้าสู่ระบบ","ชื่อ-นามสกุล","ชื่อผู้ใช้","อีเมล","รหัสผ่าน","หน้าหลัก","โปรไฟล์","เพื่อน","ข้อความ","การตั้งค่า","การแจ้งเตือน","ค้นหา SocialN...","สร้างโพสต์","คุณกำลังคิดอะไรอยู่?","เขียนความคิดเห็น...","สาธารณะ","เพื่อน","เฉพาะฉัน","ความเป็นส่วนตัว","บันทึก","บันทึกการเปลี่ยนแปลง","ยกเลิก","ลบ","ยืนยัน","แก้ไขโปรไฟล์","อัลบั้ม","สร้างอัลบั้ม","ชื่ออัลบั้ม","คำอธิบาย / บันทึก","เขียนเกี่ยวกับอัลบั้มนี้...","เพิ่มรูป/วิดีโอ","แก้ไขอัลบั้ม","ลบอัลบั้ม","เลือกสื่อ","ยังไม่มีรูปภาพหรือวิดีโอ","รูปโปรไฟล์ รูปหน้าปก และสื่อไทม์ไลน์","คำขอเป็นเพื่อน","เพื่อนของคุณ","คนที่คุณอาจรู้จัก","เพิ่มเพื่อน","ส่งข้อความ","พื้นที่จัดเก็บส่วนตัว","เริ่มการสนทนา","เลือกคนที่จะส่งข้อความ","ทำเครื่องหมายว่าอ่านแล้วทั้งหมด","รูปลักษณ์","เลือกรูปลักษณ์ SocialN ในเบราว์เซอร์นี้","สว่าง","มืด","พื้นหลังสว่าง","สบายตา","ภาษา","เลือกภาษาที่ใช้ทั่วทั้ง SocialN","เปลี่ยนชื่อผู้ใช้","เปลี่ยนรหัสผ่าน","รหัสผ่านปัจจุบัน","รหัสผ่านใหม่","ยืนยันรหัสผ่านใหม่","ประวัติย่อ","วันเกิด","บ้านเกิด","เพศ","สถานะความสัมพันธ์","ชาย","หญิง","อื่นๆ","ไม่ระบุ","ไม่ต้องการเปิดเผย","โสด","กำลังคบหา","หมั้นแล้ว","แต่งงานแล้ว","ความสัมพันธ์ซับซ้อน","ไม่มีคำขอที่รอดำเนินการ","ไม่มีโพสต์ที่มองเห็นได้","ยังไม่มีโพสต์ สร้างโพสต์แรกกันเลย","ไม่พบหน้า","ไปหน้าหลัก","ดาวน์โหลด","แสดงความรู้สึก","ส่งไฟล์","ส่งรูปภาพหรือวิดีโอ","ปิดตัวอย่าง","ตัวเลือกการสนทนา","ธีมสี","ดูรูปเต็ม","ซูม","โหลด SocialN ใหม่","SocialN พบข้อผิดพลาด UI","เลิกเป็นเพื่อน","เก็บถาวร","ปักหมุด","ลบแชท"]
};

const dictionaries={en:Object.fromEntries(en.map(x=>[x,x]))};
for(const [locale,values] of Object.entries(rows))dictionaries[locale]=Object.fromEntries(en.map((key,index)=>[key,values[index]||key]));
const extras={
  en:{"Sent requests":"Sent requests","Manage friend requests you have sent.":"Manage friend requests you have sent.","No sent requests.":"No sent requests.","Sent":"Sent","Withdraw":"Withdraw","Cancel friend request?":"Cancel friend request?","Withdraw the friend request sent to {name}?":"Withdraw the friend request sent to {name}?","Keep request":"Keep request"},
  vi:{"Sent requests":"Lời mời đã gửi","Manage friend requests you have sent.":"Quản lý các lời mời kết bạn bạn đã gửi.","No sent requests.":"Chưa có lời mời nào đã gửi.","Sent":"Đã gửi","Withdraw":"Thu hồi","Cancel friend request?":"Thu hồi lời mời kết bạn?","Withdraw the friend request sent to {name}?":"Thu hồi lời mời kết bạn đã gửi tới {name}?","Keep request":"Giữ lời mời"},
  ko:{"Sent requests":"보낸 친구 요청","Manage friend requests you have sent.":"보낸 친구 요청을 관리합니다.","No sent requests.":"보낸 친구 요청이 없습니다.","Sent":"보냄","Withdraw":"요청 취소","Cancel friend request?":"친구 요청을 취소할까요?","Withdraw the friend request sent to {name}?":"{name}님에게 보낸 친구 요청을 취소할까요?","Keep request":"요청 유지"},
  ja:{"Sent requests":"送信済みリクエスト","Manage friend requests you have sent.":"送信した友達リクエストを管理します。","No sent requests.":"送信済みのリクエストはありません。","Sent":"送信日時","Withdraw":"取り消す","Cancel friend request?":"友達リクエストを取り消しますか？","Withdraw the friend request sent to {name}?":"{name}さんへの友達リクエストを取り消しますか？","Keep request":"リクエストを保持"},
  zh:{"Sent requests":"已发送的好友请求","Manage friend requests you have sent.":"管理你已发送的好友请求。","No sent requests.":"暂无已发送的请求。","Sent":"发送于","Withdraw":"撤回","Cancel friend request?":"撤回好友请求？","Withdraw the friend request sent to {name}?":"撤回发送给 {name} 的好友请求？","Keep request":"保留请求"},
  th:{"Sent requests":"คำขอที่ส่งแล้ว","Manage friend requests you have sent.":"จัดการคำขอเป็นเพื่อนที่คุณส่งแล้ว","No sent requests.":"ไม่มีคำขอที่ส่งแล้ว","Sent":"ส่งเมื่อ","Withdraw":"ถอนคำขอ","Cancel friend request?":"ถอนคำขอเป็นเพื่อนหรือไม่?","Withdraw the friend request sent to {name}?":"ถอนคำขอเป็นเพื่อนที่ส่งถึง {name} หรือไม่?","Keep request":"เก็บคำขอไว้"}
};
for(const [locale,values] of Object.entries(extras))Object.assign(dictionaries[locale],values);
const messageMailboxExtras={
  en:{"Inbox":"Inbox","Requests":"Requests","Spam / Restricted":"Spam / Restricted","Message Requests":"Message Requests","Spam & Restricted":"Spam & Restricted","Spam":"Spam","Restricted":"Restricted","Not spam":"Not spam","Unrestrict":"Unrestrict","No message requests.":"No message requests.","No spam or restricted conversations.":"No spam or restricted conversations.","Message request":"Message request","Spam message":"Spam message","Restricted conversation":"Restricted conversation","Messages from people you are not connected with. They cannot see when you read them until you accept or reply.":"Messages from people you are not connected with. They cannot see when you read them until you accept or reply.","These conversations stay outside Inbox and do not generate normal message notifications.":"These conversations stay outside Inbox and do not generate normal message notifications.","You can read these messages privately. A Seen receipt is not sent until you accept or reply.":"You can read these messages privately. A Seen receipt is not sent until you accept or reply.","Messages stay outside Inbox. Reading does not send a Seen receipt.":"Messages stay outside Inbox. Reading does not send a Seen receipt."},
  vi:{"Inbox":"Hộp thư","Requests":"Tin nhắn chờ","Spam / Restricted":"Spam / Hạn chế","Message Requests":"Tin nhắn chờ","Spam & Restricted":"Spam và tài khoản bị hạn chế","Spam":"Spam","Restricted":"Bị hạn chế","Not spam":"Không phải spam","Unrestrict":"Bỏ hạn chế","No message requests.":"Không có tin nhắn chờ.","No spam or restricted conversations.":"Không có cuộc trò chuyện spam hoặc bị hạn chế.","Message request":"Tin nhắn chờ","Spam message":"Tin nhắn spam","Restricted conversation":"Cuộc trò chuyện bị hạn chế","Messages from people you are not connected with. They cannot see when you read them until you accept or reply.":"Tin nhắn từ những người chưa kết nối với bạn. Họ không biết bạn đã đọc cho đến khi bạn chấp nhận hoặc trả lời.","These conversations stay outside Inbox and do not generate normal message notifications.":"Các cuộc trò chuyện này nằm ngoài Hộp thư và không tạo thông báo tin nhắn thông thường.","You can read these messages privately. A Seen receipt is not sent until you accept or reply.":"Bạn có thể đọc riêng tư. Trạng thái Đã xem chỉ được gửi sau khi bạn chấp nhận hoặc trả lời.","Messages stay outside Inbox. Reading does not send a Seen receipt.":"Tin nhắn nằm ngoài Hộp thư. Việc đọc không gửi trạng thái Đã xem."}
};
for(const locale of Object.keys(dictionaries))Object.assign(dictionaries[locale],messageMailboxExtras[locale]||messageMailboxExtras.en);
const relationshipExtras={
  en:{"In a civil union":"In a civil union","In a domestic partnership":"In a domestic partnership","In an open relationship":"In an open relationship","Separated":"Separated","Divorced":"Divorced","Widowed":"Widowed","Partner (optional)":"Partner (optional)","Search for a person to tag...":"Search for a person to tag...","Remove partner":"Remove partner","Start date (optional)":"Start date (optional)","Engagement date (optional)":"Engagement date (optional)","Wedding / anniversary date (optional)":"Wedding / anniversary date (optional)","with":"with","· since":"· since"},
  vi:{"In a civil union":"Kết hợp dân sự","In a domestic partnership":"Quan hệ chung sống","In an open relationship":"Trong một mối quan hệ mở","Separated":"Ly thân","Divorced":"Đã ly hôn","Widowed":"Góa","Partner (optional)":"Người yêu/vợ/chồng (không bắt buộc)","Search for a person to tag...":"Tìm người để gắn thẻ...","Remove partner":"Xóa người được gắn thẻ","Start date (optional)":"Ngày bắt đầu (không bắt buộc)","Engagement date (optional)":"Ngày đính hôn (không bắt buộc)","Wedding / anniversary date (optional)":"Ngày cưới/kỷ niệm (không bắt buộc)","with":"với","· since":"· từ"},
  ko:{"In a civil union":"시민 결합 중","In a domestic partnership":"동거 관계 중","In an open relationship":"열린 관계 중","Separated":"별거 중","Divorced":"이혼","Widowed":"사별","Partner (optional)":"파트너 (선택)","Search for a person to tag...":"태그할 사람 검색...","Remove partner":"파트너 제거","Start date (optional)":"시작일 (선택)","Engagement date (optional)":"약혼일 (선택)","Wedding / anniversary date (optional)":"결혼/기념일 (선택)","with":"파트너","· since":"· 시작"},
  ja:{"In a civil union":"シビルユニオン","In a domestic partnership":"ドメスティックパートナーシップ","In an open relationship":"オープンな関係","Separated":"別居中","Divorced":"離婚","Widowed":"死別","Partner (optional)":"パートナー（任意）","Search for a person to tag...":"タグする人を検索...","Remove partner":"パートナーを削除","Start date (optional)":"開始日（任意）","Engagement date (optional)":"婚約日（任意）","Wedding / anniversary date (optional)":"結婚日／記念日（任意）","with":"相手","· since":"· 開始"},
  zh:{"In a civil union":"民事结合","In a domestic partnership":"同居伴侣关系","In an open relationship":"开放式关系","Separated":"分居","Divorced":"离异","Widowed":"丧偶","Partner (optional)":"伴侣（可选）","Search for a person to tag...":"搜索要标记的人...","Remove partner":"移除伴侣","Start date (optional)":"开始日期（可选）","Engagement date (optional)":"订婚日期（可选）","Wedding / anniversary date (optional)":"结婚／纪念日（可选）","with":"与","· since":"· 始于"},
  th:{"In a civil union":"จดทะเบียนคู่ชีวิต","In a domestic partnership":"คู่ชีวิตร่วมบ้าน","In an open relationship":"ความสัมพันธ์แบบเปิด","Separated":"แยกกันอยู่","Divorced":"หย่าร้าง","Widowed":"ม่าย","Partner (optional)":"คู่รัก (ไม่บังคับ)","Search for a person to tag...":"ค้นหาคนที่จะแท็ก...","Remove partner":"นำคู่รักออก","Start date (optional)":"วันที่เริ่มต้น (ไม่บังคับ)","Engagement date (optional)":"วันที่หมั้น (ไม่บังคับ)","Wedding / anniversary date (optional)":"วันแต่งงาน/วันครบรอบ (ไม่บังคับ)","with":"กับ","· since":"· ตั้งแต่"}
};
for(const [locale,values] of Object.entries(relationshipExtras))Object.assign(dictionaries[locale],values);
const relationshipWorkflowExtras={
  en:{"Accept":"Accept","Decline":"Decline","(pending)":"(pending)","{name} wants to add you to their relationship status":"{name} wants to add you to their relationship status","{name} accepted your relationship request":"{name} accepted your relationship request","{name} declined your relationship request":"{name} declined your relationship request"},
  vi:{"Accept":"Đồng ý","Decline":"Từ chối","(pending)":"(đang chờ)","{name} wants to add you to their relationship status":"{name} muốn thêm bạn vào tình trạng quan hệ của họ","{name} accepted your relationship request":"{name} đã đồng ý yêu cầu xác nhận quan hệ của bạn","{name} declined your relationship request":"{name} đã từ chối yêu cầu xác nhận quan hệ của bạn"},
  ko:{"Accept":"수락","Decline":"거절","(pending)":"(대기 중)","{name} wants to add you to their relationship status":"{name}님이 관계 상태에 회원님을 추가하려고 합니다","{name} accepted your relationship request":"{name}님이 관계 요청을 수락했습니다","{name} declined your relationship request":"{name}님이 관계 요청을 거절했습니다"},
  ja:{"Accept":"承認","Decline":"拒否","(pending)":"(承認待ち)","{name} wants to add you to their relationship status":"{name}さんが交際ステータスにあなたを追加しようとしています","{name} accepted your relationship request":"{name}さんが交際リクエストを承認しました","{name} declined your relationship request":"{name}さんが交際リクエストを拒否しました"},
  zh:{"Accept":"同意","Decline":"拒绝","(pending)":"（待确认）","{name} wants to add you to their relationship status":"{name} 想将你添加到其感情状态中","{name} accepted your relationship request":"{name} 已同意你的关系确认请求","{name} declined your relationship request":"{name} 已拒绝你的关系确认请求"},
  th:{"Accept":"ยอมรับ","Decline":"ปฏิเสธ","(pending)":"(รอการยืนยัน)","{name} wants to add you to their relationship status":"{name} ต้องการเพิ่มคุณในสถานะความสัมพันธ์","{name} accepted your relationship request":"{name} ยอมรับคำขอความสัมพันธ์ของคุณแล้ว","{name} declined your relationship request":"{name} ปฏิเสธคำขอความสัมพันธ์ของคุณ"}
};
for(const [locale,values] of Object.entries(relationshipWorkflowExtras))Object.assign(dictionaries[locale],values);
const friendSearchLabels={en:"Search your friends to tag...",vi:"Tìm trong danh sách bạn bè để gắn thẻ...",ko:"태그할 친구 검색...",ja:"タグする友達を検索...",zh:"搜索要标记的好友...",th:"ค้นหาเพื่อนที่จะแท็ก..."};
for(const [locale,label] of Object.entries(friendSearchLabels))dictionaries[locale]["Search for a person to tag..."]=label;
const groupWelcomeLabels={en:"Welcome to {name}",vi:"Chào mừng bạn đến với nhóm {name}",ko:"{name} 그룹에 오신 것을 환영합니다",ja:"{name}グループへようこそ",zh:"欢迎加入{name}小组",th:"ยินดีต้อนรับสู่กลุ่ม {name}"};
for(const [locale,label] of Object.entries(groupWelcomeLabels))dictionaries[locale]["Welcome to {name}"]=label;
let current="en",observer=null,applying=false;
const textState=new WeakMap(),attrState=new WeakMap();
const ignored=".post-content,.comment-body,.bubble,.profile-bio,.shared-content,.album-card small,.album-modal-title p";
function translated(value){
  const trimmed=value.trim(),hit=dictionaries[current]?.[trimmed];
  if(hit)return value.replace(trimmed,hit);
  if(trimmed.startsWith("Sent "))return value.replace(trimmed,`${dictionaries[current]?.Sent||"Sent"} ${trimmed.slice(5)}`);
  const withdraw=trimmed.match(/^Withdraw the friend request sent to (.+)\?$/);
  if(withdraw)return value.replace(trimmed,translate("Withdraw the friend request sent to {name}?",{name:withdraw[1]}));
  if(trimmed.startsWith("Welcome to "))return value.replace(trimmed,translate("Welcome to {name}",{name:trimmed.slice(11)}));
  for(const template of ["{name} wants to add you to their relationship status","{name} accepted your relationship request","{name} declined your relationship request"]){const suffix=template.replace("{name}","");if(trimmed.endsWith(suffix))return value.replace(trimmed,translate(template,{name:trimmed.slice(0,-suffix.length)}))}
  return value;
}
export function translate(key,params={}){let value=dictionaries[current]?.[key]||key;for(const [name,replacement] of Object.entries(params))value=value.replaceAll(`{${name}}`,replacement);return value}
function scan(root=document.body){
  if(!root)return;applying=true;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
  while((node=walker.nextNode())){if(!node.nodeValue.trim()||node.parentElement?.closest(ignored))continue;let state=textState.get(node);if(!state||node.nodeValue!==state.rendered)state={source:node.nodeValue,rendered:node.nodeValue};const next=translated(state.source);state.rendered=next;textState.set(node,state);if(node.nodeValue!==next)node.nodeValue=next}
  const elements=[...(root.nodeType===1?[root]:[]),...(root.querySelectorAll?.("[placeholder],[title],[aria-label]")||[])];
  for(const el of elements){let states=attrState.get(el)||{};for(const attr of ["placeholder","title","aria-label"]){if(!el.hasAttribute?.(attr))continue;const value=el.getAttribute(attr),old=states[attr];if(!old||value!==old.rendered)states[attr]={source:value,rendered:value};const next=translated(states[attr].source);states[attr].rendered=next;if(value!==next)el.setAttribute(attr,next)}attrState.set(el,states)}
  applying=false;
}
export function setSiteLanguage(locale){current=dictionaries[locale]?locale:"en";document.documentElement.lang=current;localStorage.setItem("socialn_language",current);scan();if(!observer){observer=new MutationObserver(mutations=>{if(applying)return;for(const mutation of mutations)scan(mutation.type==="characterData"?mutation.target.parentElement:mutation.target)});observer.observe(document.body,{subtree:true,childList:true,characterData:true})}}
